### ISSUE TITLE
Silkworm?

### ISSUE THREAD

**Issue by FranckKnight** [SoftDFurry/WaterBlock#2]
I knocked down some 20 trees and not a single silkworm. Was it forgotten?

I usually get 2-3 per trees that I crook down in other modpacks.

**Comment by SoftDFurry** [comment]
I tried to reproduce the bug and it was successful. I have disabled the other crooks as a workaround for now until I can find a fix for the crooks. Further contact with the Ex Nihilo devs may be needed, but the other crooks I have made work now. I am so sorry for the buggy release

**Comment by FranckKnight** [comment]
No problem, I'm sure that all new modpacks go through oddities like that too.

It just stumped me pretty early since the 3rd quest in the book is making string and the strainer, that was a quick stop.

**Comment by SoftDFurry** [comment]
I made a new update btw.
